version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - nginx_network
    depends_on:
      - app1
      - app2
      - app3
      - app4

  app1:
    build: ./app1  # Verifica que esta ruta sea correcta
    networks:
      - nginx_network

  app2:
    build: ./app2  # Verifica que esta ruta sea correcta
    networks:
      - nginx_network

  app3:
    build: ./app3  # Verifica que esta ruta sea correcta
    networks:
      - nginx_network

  app4:
    build: ./app4  # Verifica que esta ruta sea correcta
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

